service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::csv-parser-bucket-2023"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::csv-parser-bucket-2023/*"
    - Effect: Allow
      Action: sqs:*
      Resource:
        # - Fn::ImportValue: "SQSQueueArn"
        - "arn:aws:sqs:us-east-1:457593347727:catalogItemsQueue"
  environment:
    IMPORT_BUCKET: csv-parser-bucket-2023
    SQS_URL: https://sqs.us-east-1.amazonaws.com/457593347727/catalogItemsQueue
    # SQS_URL: {"Fn::ImportValue": "SQSQueueUrl"}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import/{fileName}
          method: get
          cors: true
          authorizer: arn:aws:lambda:us-east-1:457593347727:function:authorization-service-dev-basicAuthorizer

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: csv-parser-bucket-2023
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
