service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::csv-parser-bucket-2023"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::csv-parser-bucket-2023/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import/{fileName}
          method: get

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: csv-parser-bucket-2023
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
